# Language and NumPy basics

***
## Basic syntax

-   Everything after a `#` character (until the end of the line) is a comment and will be ignored.
-   Variables are created using the assignment operator `=`.
-   Variable names are case sensitive.
-   Whitespace characters matter (unlike in most languages)!
-   Python uses indentation (usually 4 spaces) to group statements,
    for example loop bodies, functions, etc.
-   You can use the `print()` function to inspect almost any object.

In [6]:
# This is a comment

var = "Hello, World!"
x = 1.0
print(x)
var 

1.0


'Hello, World!'

***
## Built-in data types

Pythons is a dynamically-typed language:

-   No need to declare a variable or its type
-   You can inspect a variable's type using the built-in `type()` function

**Basic types**

- integers (`int`)
- floating-point numbers (`float`)
- boolean (`bool`)
- strings (`str`)

**Containers (or collections)**

- tuples (`tuple`)
- lists (`list`)
- dictionaries (`dict`)

In [8]:
x = 1

In [9]:
type(x)

int

***
### Numerical data types

#### Integers and floats

- **Integers:** created from literal values *without* decimal dot
- **Floats:** created from literal values *with* decimal dot or scientific notation (e.g., $5 \times 10^{-8}$ is written as `5e-8`)
- Optional _ as thousands separator

In [10]:
x = 1e-8

In [11]:
x

1e-08

#### Booleans

- Created using the keywords `True` and `False`

In [14]:
x = 1 == 1

In [13]:
x

True

<div class="alert alert-info">
<h3> Your turn</h3>
Floating-point numbers cannot represent real numbers with arbitrary precision. This can lead to surprising results:
<ol>
    <li>Define the floating-point number <tt>x</tt> with value <tt>1/3</tt>.</li>
    <li>Add <tt>x</tt> three times (<tt>x + x + x</tt>) and print the result.</li>
    <li>Add <tt>x</tt> six times and print the result.</li>
    <li>Rewrite the above expression as <tt>(x + x + x) + (x + x + x)</tt> and print the result.</li>
    <li>Add the floating-point numbers <tt>1.0</tt> and <tt>10<sup>-15</sup></tt> and print the result.
    What happens if you add <tt>1.0</tt> and <tt>10<sup>-16</sup></tt> instead?</li>
</ol>
</div>

In [19]:
x = 1/3
x

0.3333333333333333

In [20]:
x+x+x

1.0

In [22]:
x+x+x+x+x+x

1.9999999999999998

In [23]:
(x+x+x) + (x+x+x)

2.0

In [24]:
x = 1.0
eps = 1.0e-16
x + eps

1.0

***
### Strings

- The string (`str`) data type is used to store text
- Enclosed in either `'` or `"`

In [ ]:
institution = "NHH"
institution = 'NHH'

#### Sting operations

- Can be concatenated with `+`
- Can be duplicated with `*`

In [25]:
s1 = 'Python' 
s2 ='Course'

s1 + s2

'PythonCourse'

#### Formatting with f-strings

In [27]:
pi = 3.14159
f'Pi is approximately {pi:.2f}'

'Pi is approximately 3.14'

<div class="alert alert-info">
<h3> Your turn</h3>
Continuing our experiments with floating-point numbers, perform the following tasks:
<ol>
    <li>Define the floating-point number <tt>x</tt> with value <tt>1/3</tt>, 
        and use an f-string to print it with 20 decimal digits.</li>
    <li>Define the floating-point number <tt>x</tt> with value <tt>0.1</tt>, 
        and use an f-string to print it with 20 decimal digits.</li>
</ol>

As you can see, problems not only arise if a real number has infinitely many 
decimal digits (like 1/3), but also if it cannot be exactly represented as a binary number (base-2).
</div>

In [28]:
x = 1/3
f'x is {x:.20f}'

'x is 0.33333333333333331483'

In [29]:
x = 0.1
f'x is {x:.20f}'

'x is 0.10000000000000000555'

***
### Tuples

- *ordered, immutable collection* of items which can
have different data types
- Created using `,`
- Optionally enclosed in `()`
- Elements are accessed using `[]`
- Index is 0-based
- Built-in `len()` function returns number of items

In [41]:
x = (1, 1.0, "Hello")
x

(1, 1.0, 'Hello')

In [42]:
x[0]

1

In [43]:
len(x)

3

In [44]:
# This does not work
x[0] = "Hei"

TypeError: 'tuple' object does not support item assignment

***
### Lists

- Like tuples, but can be modified (*mutable*)
- Can use methods to modify lists: `append()`, `insert()`, ...

In [65]:
x =[1, 1.0, "Hello"]

In [66]:
x

[1, 1.0, 'Hello']

In [67]:
x[0] = "Hei"

In [68]:
x

['Hei', 1.0, 'Hello']

In [69]:
x.append("World")

In [71]:
x

['Hei', 1.0, 'Hello', 'World']

In [72]:
x.insert(1, "Python")

In [73]:
x

['Hei', 'Python', 1.0, 'Hello', 'World']

<div class="alert alert-info">
<h3> Your turn</h3>
Perform the following tasks to practice working with lists:
<ol>
    <li>Define a tuple containing a single value <tt>'a'</tt>.</li>
    <li>Convert the tuple to a list using the <a href="https://www.w3schools.com/python/ref_func_list.asp"><tt>list()</tt></a> function.</li>
    <li>Append the items <tt>'b'</tt> and <tt>'c'</tt> using the <a href="https://www.w3schools.com/python/ref_list_append.asp"><tt>append()</tt></a> method.</li>
    <li>Select the last element of the list. Determine the index of this last element using 
    the <tt>len()</tt> function.</li>
</ol>
</div>

In [78]:
t = ("a",)


In [79]:
t = list(t)

In [81]:
# Append items 'b' and 'c' to the list
t.append("b")
t.append("c")

In [ ]:
length = round(len(t), 0)
print(t)
t[length-1] # This is the last element, but not the best way to do it
t[-1] # This is the last element, better way to do it

['a', 'b', 'c', 'b', 'c']


'c'

***
### Dictionaries

- Map keys to values (keys don't have to be integers, unlike tuples, lists,...)
- Can be created using `{key: value}` syntax
- Alternatively created using `dict()`
- Elements are accessed using `[key]` 
- Methods `.keys()` and `.values()` return keys and values in dictionary

In [94]:
d = {'institution': 'NHH', 'course': 'FIE463'}

In [95]:
d

{'institution': 'NHH', 'course': 'FIE463'}

In [96]:
d = dict(institution='NHH', course='FIE463')

In [97]:
d

{'institution': 'NHH', 'course': 'FIE463'}

In [98]:
d['course']

'FIE463'

In [100]:
d.get('term', "Spring 2021") # If the key does not exist, return the default value

'Spring 2021'

In [101]:
len(d)

2

***
## NumPy arrays


-   Data type to efficiently store numeric data
-   NumPy is *not* part of the core Python project
-   Must be imported prior to use: `import numpy as np`

In [102]:
import numpy as np

### Creating arrays

In [103]:
lst = [1, 2, 3, 4, 5]

In [104]:
arr = np.array(lst)

In [105]:
arr

array([1, 2, 3, 4, 5])

#### Creating arrays from other Python objects

- Can be created from other sequence objects such as tuples or lists using [`np.array()`](https://numpy.org/doc/stable/reference/generated/numpy.array.html)

In [106]:
np.array((1, 2, 3, 4, 5))

array([1, 2, 3, 4, 5])

#### Array creation routines

Functions to create arrays from scratch:

-   [`np.zeros()`](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html) 
    creates an array of a given shape and initializes it
    to zeros.
-   [`np.ones()`](https://numpy.org/doc/stable/reference/generated/numpy.ones.html) 
    creates an array of a given shape and initializes it
    to ones.
-   [`np.arange(start,stop,step)`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) 
    creates an array with evenly spaced
    elements over the range $[start,stop)$.
    -   `start` and `step` can be omitted and then default to `start=0` and `step=1`.
    -   Note that the number `stop` is never included in
        the resulting array!
-   [`np.linspace(start,stop,num)`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) 
    returns a vector of `num` elements
    which are evenly spaced over the interval $[start,stop]$.

There are many more array creation functions for more exotic use-cases,
see the NumPy  [documentation](https://numpy.org/doc/stable/reference/routines.array-creation.html)
for details.

In [107]:
np.zeros(3)

array([0., 0., 0.])

In [108]:
np.zeros((3, 2)) # 2 Columns, 3 Rows # With zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [111]:
np.ones((3, 2)) # 2 Columns, 3 Rows # With ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [110]:
np.arange(1, 10, 2) # Start, Stop, Step

array([1, 3, 5, 7, 9])

In [112]:
np.linspace(0, 1, 6) # Start, Stop, Number of elements # 0 to 1 with 6 elements

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

<div class="alert alert-info">
<h3> Your turn</h3>
Lists and NumPy arrays behave differently in potentially unexpected ways. 
Perform the following tasks and inspect the result for both list and array arguments.
<ol>
    <li>Create two variables, a list and a NumPy array, both containing the elements <tt>[1, 2, 3]</tt>.</li>
    <li>Multiply the list and the array by 2.</li>
    <li>Add <tt>[4]</tt> to both the list and the array.</li>
    <li>Add <tt>4</tt> to both the list and the array. Does this work?</li>
</ol>
</div>

### Reshaping arrays

- The `reshape()` method reshape array to some other (conformable) shape
- Can be used to create lower- or higher-dimensional arrays
- One dimension in shape can be omitted using `-1`

***
### Indexing

#### Single element indexing

-   NumPy arrays use 0-based indices
-   Unlike lists or tuples, NumPy arrays support multi-dimensional
    indexing
-   Use `arr[i, j]`, *not* `arr[i][j]`

#### Index slices

- Slicing with `start:stop:step` syntax retrieves ranges of elements.

*Rules:*

-   all tokens in `start:stop:step` are optional, with
    the obvious default values.
    We could therefore write `::` to include all indices,
    which is the same as `:`
- The end value is *not* included. Writing
  `vec[0:n]` does not include element with index $n$!
- Any of the elements of `start:stop:step` can be negative.
    - If `start` or `stop` are negative, elements are counted
        from the end of the array:
        `vec[:-1]` retrieves the whole vector except for the last element.
    - If `step` is negative, the order of elements is reversed.

<div class="alert alert-info">
<h3> Your turn</h3>
Perform the following tasks to practice working with NumPy arrays:
<ol>
    <li>Create a NumPy array containing the sequence from 5 to 100 (inclusive).</li>
    <li>Select and print every 5th element from the array.</li>
    <li>Select the last element in two different ways without hardcoding the index.
    <br/><it>Hint:</it> The function <tt>len()</tt> also works for NumPy arrays.</li>
</ol>
</div>

***
### Numerical data types (advanced)

- Most array creation routines support `dtype` argument to specify data type
- Valid values: `int`, `float`, `np.float64`, `np.float32`, `np.int64`, `np.int32`, ...
- Use data type that is appropriate for the task!